ipvisionCrmApi/ViewModels/IntegrationSettings/CreateEditVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ipvisionCrmApi.ViewModels.IntegrationSettings
{
    public class CreateEditVm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
    }
}

ipvisionCrmApi/ViewModels/IntegrationSettings/IndexVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.Data;

namespace ipvisionCrmApi.ViewModels.IntegrationSettings
{
    public class IndexVm
    {
        public List<CrmUri> CrmUris { get; set; }

    }
}

ipvisionCrmApi/ViewModels/IntegrationSettings/SelectContactUrlVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.Data;

namespace ipvisionCrmApi.ViewModels.IntegrationSettings
{
    public class SelectContactUrlVm
    {
        public List<InternalCrmContact> Contacts { get; set; }
        public string Uri { get; set; }
    }
}

ipvisionCrmApi/Controllers/IntegrationSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ipvisionCrmApi.Data;
using ipvisionCrmApi.Extensions;
using ipvisionCrmApi.Integrations.Zendesk;
using ipvisionCrmApi.ViewModels.IntegrationSettings;
using Microsoft.Ajax.Utilities;

namespace ipvisionCrmApi.Controllers
{
    [Authorize]
    public class IntegrationSettingsController : Controller
    {
        // GET: Integrations
        public async Task<ActionResult> Index()
        {
            var customerId = User.UserId();

            var vm = new IndexVm();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customer = await db.Customers.SingleAsync(x => x.Id == customerId);
                vm.CrmUris = await db.CrmUris.Where(x => x.CustomerId == customerId).ToListAsync();

            }
            return View(vm);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var customerId = User.UserId();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var uri = await db.CrmUris.SingleAsync(x => x.Id == id && x.CustomerId == customerId);
                if (uri.ZendeskConnectorId != null)
                {
                    return RedirectToAction("CreateEditZendeskConnector", new {id = uri.Id});
                }

                return View("CreateEditIntegration", uri);
            }
        }

        public async Task<ActionResult> Create()
        {
            return View("CreateEditIntegration", new CrmUri());
        }

        public async Task<ActionResult> CreateEditZendeskConnector(int? id = null)
        {
            var customerId = User.UserId();
            var vm = new CrmUri();
            if (id != null)
            {
                using (var db = new IpvisionCrmApiDbEntities())
                {
                    vm = await db.CrmUris.Where(x =>
                        x.Id == id && x.ZendeskConnectorId != null && x.CustomerId == customerId)
                        .Include(x => x.ZendeskConnector.CrmUris)
                        .SingleAsync();
                }
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> CreateEditZendeskConnector(CrmUri model)
        {
            var customerId = User.UserId();

            using (var db = new IpvisionCrmApiDbEntities())
            {
                var existing = await db.CrmUris.FirstOrDefaultAsync(x => x.CustomerId == customerId && x.Id == model.Id);
                if (existing != null)
                {
                    existing.Uri = "";
                    existing.Name = model.Name;
                    existing.ZendeskConnector.Email = model.ZendeskConnector.Email;
                    existing.ZendeskConnector.ApiToken = model.ZendeskConnector.ApiToken;
                    existing.ZendeskConnector.ZendeskUrl = model.ZendeskConnector.ZendeskUrl;
                }
                else
                {
                    var connectorDbo = db.ZendeskConnectors.Add(new ZendeskConnector()
                    {
                        ZendeskUrl = model.ZendeskConnector.ZendeskUrl,
                        Email = model.ZendeskConnector.Email,
                        ApiToken = model.ZendeskConnector.ApiToken,
                    });
                    await db.SaveChangesAsync();

                    db.CrmUris.Add(new CrmUri()
                    {
                        CustomerId = customerId,
                        CreatedDate = DateTime.Now,
                        Uri = "",
                        Name = model.Name,
                        ZendeskConnectorId = connectorDbo.Id
                    });
                }

                await db.SaveChangesAsync();
            }

            TempData["SuccessMessage"] = "Zendesk Connector oprettet";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(FormCollection form)
        {
            var id = Convert.ToInt32(form["id"]);
            var customerId = User.UserId();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var uri = await db.CrmUris.SingleAsync(x => x.Id == id && x.CustomerId == customerId);
                if (uri.ZendeskConnectorId != null)
                {
                    db.ZendeskConnectors.Remove(uri.ZendeskConnector);
                }
                db.CrmUris.Remove(uri);
                await db.SaveChangesAsync();

                TempData["SuccessMessage"] = "Integration slettet";

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CreateEditVm model)
        {
            var customerId = User.UserId();

            using (var db = new IpvisionCrmApiDbEntities())
            {
                var existing = await db.CrmUris.FirstOrDefaultAsync(x => x.CustomerId == customerId && x.Id == model.Id);
                if (existing != null)
                {
                    existing.Uri = model.Uri;
                    existing.Name = model.Name;
                }
                else
                {
                    db.CrmUris.Add(new CrmUri()
                    {
                        CustomerId = customerId,
                        CreatedDate = DateTime.Now,
                        Uri = model.Uri,
                        Name = model.Name
                    });
                }

                await db.SaveChangesAsync();
            }

            TempData["SuccessMessage"] = "Ændringer gemt";

            return RedirectToAction("Index");
        }



        [AllowAnonymous]
        public async Task<ActionResult> OpenUrl(Guid customerId, string callerId, int urlId)
        {
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var finalContacts = new List<InternalCrmContact>();
                var vm = new SelectContactUrlVm();
                var uri = await db.CrmUris.FirstOrDefaultAsync(x => x.CustomerId == customerId && x.Id == urlId);
                if (uri == null)
                {
                    return View("NoUriSet");
                }
                //Step 1: Check if the URI is a zendesk Connector
                if (uri.ZendeskConnector != null)
                {

                    try
                    {
                        var zendeskUsers = ZendeskApiConsumer.SearchUsers(uri.ZendeskConnector.Email,
                        uri.ZendeskConnector.ApiToken, uri.ZendeskConnector.ZendeskUrl, callerId);
                        if (zendeskUsers != null)
                        {
                            foreach (var user in zendeskUsers)
                            {
                                finalContacts.Add(new InternalCrmContact()
                                {
                                    Email = user.email,
                                    CustomerId = customerId,
                                    Name = user.name,
                                    InternalCrmId1 = user.id.ToString(),
                                    Phone1 = user.phone,

                                });
                            }
                        }
                    }
                    catch (Exception e)
                    {
                        TempData["ErrorMessage"] = e.Message;
                        return View("SelectContact", vm);
                    }

                    vm.Uri = $"{uri.ZendeskConnector.ZendeskUrl}/agent/users/[internalCrmId1]/requested_tickets";
                    vm.Contacts = finalContacts;
                    if (!finalContacts.Any())
                    {
                        return Redirect($"{uri.ZendeskConnector.ZendeskUrl}/agent/tickets/new/1");
                    }

                    if (finalContacts.Count == 1)
                    {
                        var finalUri = vm.Uri
                            .Replace("[internalCrmId1]", finalContacts.First().InternalCrmId1);
                        return Redirect(finalUri);
                    }
                    else
                    {
                        return View("SelectContact", vm);
                    }


                }


                //Otherwise, check in contacts
                var contacts =
                    await db.InternalCrmContacts.Where(x => x.CustomerId == customerId && x.Phone1 == callerId || x.Phone2 == callerId || x.Phone3 == callerId || x.Phone4 == callerId).ToListAsync();




                var crmIdPlaceHolders = uri.Uri.Split('[', ']').ToList();
                crmIdPlaceHolders = crmIdPlaceHolders.Where(x => x.Contains("internalCrmId")).ToList();

                if (!contacts.Any())
                {
                    return View("NoContactFound");
                }

 
                foreach (var contact in contacts)
                {
                    if (crmIdPlaceHolders.Contains($"internalCrmId1") && !string.IsNullOrEmpty(contact.InternalCrmId1))
                    {
                        finalContacts.Add(contact);
                        continue;
                    }

                    if (crmIdPlaceHolders.Contains($"internalCrmId2") && !string.IsNullOrEmpty(contact.InternalCrmId2))
                    {
                        finalContacts.Add(contact);
                        continue;
                    }

                    if (crmIdPlaceHolders.Contains($"internalCrmId3") && !string.IsNullOrEmpty(contact.InternalCrmId3))
                    {
                        finalContacts.Add(contact);
                        continue;
                    }

                    if (crmIdPlaceHolders.Contains($"internalCrmId4") && !string.IsNullOrEmpty(contact.InternalCrmId4))
                    {

ipvisionCrmApi/Views/IntegrationSettings/CreateEditIntegration.cshtml
@model ipvisionCrmApi.Data.CrmUri
@{
    ViewBag.Title = "CreateEditIntegration";
}
@section styles{
    <link href="/assets/css/pages/pricing/pricing-1.min.css" rel="stylesheet" type="text/css" />
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Opsæt integration
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="@Url.Action("Index")" class="kt-subheader__breadcrumbs-link">
                    CRM URL-opslag
                </a>
            </div>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col">
            <div class="alert alert-light alert-elevate fade show" role="alert">
                <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
                <div class="alert-text">
                    I nedenstående formular skal du blot indtaste den URL der skal åbnes, når en kontakt ringer jer op.
                    <br />
                    Du kan bruge CRM ID'erne fra dine kontakter: [internalCrmId1], [internalCrmId2], [internalCrmId3], [internalCrmId4], [internalCrmId5] og [internalCrmId6] som flettefelter i URL'en.
                    <br />
                    Eksempel: @($"https://company.zendesk.com/agent/users/")<strong>[internalCrmId1]</strong>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Indstil URL her
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Edit", "IntegrationSettings", FormMethod.Post))
                            {
                                @Html.HiddenFor(x => x.Id)
                                <div class="form-group">
                                    <label>Navn på integration (Vises hos brugerne i pop-up klienten)</label>
                                    <input type="text" required="required" class="form-control" name="Name" value="@(Model?.Name)"/>
                                </div>
                                <div class="form-group">
                                    <label>URL</label>
                                    <input type="text" required="required" class="form-control" name="Uri" value="@(Model?.Uri)"/>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-success">@(Model == null ? "Opret" : "Gem ændring")</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <span class="kt-portlet__head-icon">
                            <i class="la la-puzzle-piece"></i>
                        </span>
                        <h3 class="kt-portlet__head-title">
                            Eller opsæt en CRM connector
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="kt-pricing-1 kt-pricing-1--fixed">
                        <div class="kt-pricing-1__items row">
                            <div class="kt-pricing-1__item col-lg-12">
                                <div class="kt-pricing-1__visual">
                                    <img src="/assets/media/logos/zendesk.svg" width="200"/>
                                </div>
                                <span class="kt-pricing-1__price" style="margin-top:0">Zendesk Connector</span>
                                <h2 class="kt-pricing-1__subtitle">Integration til Zendesk</h2>
                                <span class="kt-pricing-1__description">
                                    <span>Opsæt en direkte integration til Zendesk.</span>
                                    <span>Integrationen vil nu lave et opslag direkte i</span>
                                    <span>Zendesk når jeres kunder ringer</span>
                                </span>
                                <div class="kt-pricing-1__btn">
                                    <a href="@Url.Action("CreateEditZendeskConnector","IntegrationSettings")" class="btn btn-pill  btn-brand btn-wide btn-uppercase btn-bolder btn-sm">Opsæt nu</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ipvisionCrmApi/Views/IntegrationSettings/CreateEditZendeskConnector.cshtml
@using ipvisionCrmApi.Extensions
@model ipvisionCrmApi.Data.CrmUri
@{
    ViewBag.Title = "Zendesk Connector";
}

<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Opsæt Zendesk Connecter
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="@Url.Action("Index")" class="kt-subheader__breadcrumbs-link">
                    CRM URL-opslag
                </a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="@Url.Action("Create","IntegrationSettings")" class="kt-subheader__breadcrumbs-link">
                    Ny integration
                </a>
            </div>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-12">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Indstil Connector her
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("CreateEditZendeskConnector", "IntegrationSettings", FormMethod.Post))
                            {

                                @Html.HiddenFor(x => x.Id)
                                <div class="form-group">
                                    <label>Navn på integration (Vises hos brugerne i pop-up klienten)</label>
                                    <input type="text" required="required" class="form-control" name="Name" value="@(Model?.Name)"/>
                                </div>
                                <div class="form-group">
                                    <label>Zendesk URL</label>
                                    <input type="text" required="required" class="form-control" name="ZendeskConnector.ZendeskUrl" value="@(Model?.ZendeskConnector?.ZendeskUrl)"/>
                                    <span class="small">Eksempelvis: https://company.zendesk.com</span>
                                </div>
                                <div class="form-group">
                                    <label>Brugernavn</label>
                                    <input type="text" required="required" class="form-control" name="ZendeskConnector.Email" value="@(Model?.ZendeskConnector?.Email)"/>
                                    <span class="small">Zendesk brugernavn</span>
                                </div>
                                <div class="form-group">
                                    <label>Password / API Token</label>
                                    <input type="text" required="required" class="form-control" name="ZendeskConnector.ApiToken" value="@(Model?.ZendeskConnector?.ApiToken)"/>
                                    <span class="small">Zendesk password / API token</span>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-success">@(Model == null ? "Opret" : "Gem ændring")</button>
                                </div>
                            }
                            @if (Model?.ZendeskConnector != null)
                            {
                                using (Html.BeginForm("OpenUrl", "IntegrationSettings", FormMethod.Get, new {target = "_blank"}))
                                {
                                    <br/>
                                    <hr/>
                                    <br/>
                                    <input type="hidden" name="customerId" value="@User.UserId()"/>
                                    <input type="hidden" name="urlId" value="@Model.ZendeskConnector.CrmUris.First().Id" />
                                    <div class="form-group">
                                        <label>Test integration.</label>
                                        <input type="text" required="required" class="form-control" name="callerId" value="" placeholder="Telefonnummer"/>
                                        <span class="small">Skriv et telefonnummer for at emulere et opslag i zendesk</span>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-lg btn-info">Test integration</button>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ipvisionCrmApi/Views/IntegrationSettings/Index.cshtml
@model ipvisionCrmApi.ViewModels.IntegrationSettings.IndexVm
@{
    ViewBag.Title = "Integrationsopsætning";
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Opsæt integrationer
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="@Url.Action("Index")" class="kt-subheader__breadcrumbs-link">
                    CRM URL-opslag
                </a>
            </div>
        </div>
    </div>
</div>
<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row" style="margin:20px 0">
        <div class="col-12">
            <a href="@Url.Action("Create")" class="btn btn-lg btn-success">Opret ny</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">

            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Integrationer
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <table class="table table-striped- table-bordered table-hover table-registrations" id="kt_table_1">
                        <thead>
                        <tr>
                            <th>Url</th>
                            <th>Navn</th>
                            <th>Rediger</th>
                            <th>Slet</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach (var uri in Model.CrmUris)
                        {
                            <tr>
                                <td>@uri.Uri</td>
                                <td>@uri.Name</td>
                                <td><a href="@Url.Action("Edit", new {id = uri.Id})" class="btn btn-success">Rediger</a></td>
                                <td>
                                    @using (Html.BeginForm("Delete", "IntegrationSettings", FormMethod.Post))
                                    {
                                        <input type="hidden" name="id" value="@uri.Id"/>
                                        <button type="submit" class="btn btn-danger">Slet</button>
                                    }
                                </td>
                            </tr>
                        }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>


</div>

ipvisionCrmApi/Views/IntegrationSettings/NoContactFound.cshtml
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewBag.Title = "Kontakt ikke fundet";
}

<div class="kt-login__logo">
    <a href="/">
        <img width="200" src="@Url.Content("~/assets/media/logos/logo.png")">
    </a>
</div>
<div class="kt-login__signin">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Der opstod en fejl!</h3>
    </div>
    <div class="kt-form">
        <div id="login-content">
            <div class="alert alert-danger fade show" role="alert">
                <div class="alert-icon"><i class="flaticon-warning"></i></div>
                <div class="alert-text">Der blev ikke fundet nogen kontakt</div>
                <div class="alert-close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="la la-close"></i></span>
                    </button>
                </div>
            </div>

        </div>
    </div>
</div>

ipvisionCrmApi/Views/IntegrationSettings/NoUriSet.cshtml
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewBag.Title = "No Url Set";
}

<div class="kt-login__logo">
    <a href="/">
        <img width="200" src="@Url.Content("~/assets/media/logos/logo.png")">
    </a>
</div>
<div class="kt-login__signin">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Der opstod en fejl!</h3>
    </div>
    <div class="kt-form">
        <div id="login-content">
            <div class="alert alert-danger fade show" role="alert">
                    <div class="alert-icon"><i class="flaticon-warning"></i></div>
                    <div class="alert-text">Der er ikke indstillet en integrations-URL på jeres konto</div>
                    <div class="alert-close">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="la la-close"></i></span>
                        </button>
                    </div>
                </div>

        </div>
    </div>
</div>

ipvisionCrmApi/Views/IntegrationSettings/SelectContact.cshtml
@model ipvisionCrmApi.ViewModels.IntegrationSettings.SelectContactUrlVm
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewBag.Title = "No Url Set";
}

<div class="kt-login__logo">
    <a href="/">
        <img width="200" src="@Url.Content("~/assets/media/logos/logo.png")">
    </a>
</div>
<div class="kt-login__signin">
    <div class="kt-login__head">
        <h3 class="kt-login__title">Vælg kontakt</h3>
    </div>
    <div class="kt-form">
        <div id="login-content">
            @if (TempData["ErrorMessage"] == null)
            {


                <div class="alert alert-success fade show" role="alert">
                    <div class="alert-icon"><i class="flaticon2-check-mark"></i></div>
                    <div class="alert-text">Der blev fundet flere kontakter. Vælg den korrekte</div>
                    <div class="alert-close">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="la la-close"></i></span>
                        </button>
                    </div>
                </div>
            }
            else
            {
                <div class="alert alert-danger fade show" role="alert">
                    <div class="alert-icon"><i class="flaticon2-exclamation"></i></div>
                    <div class="alert-text">@TempData["ErrorMessage"]</div>
                    <div class="alert-close">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="la la-close"></i></span>
                        </button>
                    </div>
                </div>
            }
            @if (Model != null && Model.Contacts != null)
            {
                foreach (var contact in Model.Contacts)
                {
                    var finalUrl = Model.Uri
                        .Replace("[internalCrmId1]", contact.InternalCrmId1)
                        .Replace("[internalCrmId2]", contact.InternalCrmId2)
                        .Replace("[internalCrmId3]", contact.InternalCrmId3)
                        .Replace("[internalCrmId4]", contact.InternalCrmId4)
                        .Replace("[internalCrmId5]", contact.InternalCrmId5)
                        .Replace("[internalCrmId6]", contact.InternalCrmId6);
                    <div class="kt-login__actions">
                        <a href="@finalUrl" class="btn btn-brand btn-elevate kt-login__btn-primary">@contact.Name
                        @if (!string.IsNullOrEmpty(contact.Email))
                        {
                            <span>(@contact.Email)</span>
                        }
                        </a>
                    </div>
                }
            }
        </div>
    </div>
</div>