ipvisionCrmApi/ViewModels/ClientSettings/EditVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ipvisionCrmApi.ViewModels.ClientSettings
{
    public class EditVm
    {
        public string DefaultIncomingOpenUrl { get; set; }
        public string DefaultOutgoingOpenUrl { get; set; }
    }
}

ipvisionCrmApi/ViewModels/ClientSettings/SubModels/UserWithStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.Integrations.ipvision.Models;

namespace ipvisionCrmApi.ViewModels.ClientSettings.SubModels
{
    public class UserWithStatus
    {
        public MitelUserModel MitelUser { get; set; }
        public bool IsDisabled { get; set; }
    }
}

ipvisionCrmApi/ViewModels/ClientSettings/UsersVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.ViewModels.ClientSettings.SubModels;

namespace ipvisionCrmApi.ViewModels.ClientSettings
{
    public class UsersVm
    {
        public List<UserWithStatus> Users { get; set; }
    }
}

ipvisionCrmApi/Controllers/ClientSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ipvisionCrmApi.Data;
using ipvisionCrmApi.Extensions;
using ipvisionCrmApi.Integrations.ipvision;
using ipvisionCrmApi.ViewModels.ClientSettings;
using ipvisionCrmApi.ViewModels.ClientSettings.SubModels;
using ipvisionCrmApi.ViewModels.IntegrationSettings;

namespace ipvisionCrmApi.Controllers
{
    [Authorize]
    public class ClientSettingsController : Controller
    {
        // GET: ClientSettings
        public async Task<ActionResult> Index()
        {
            var customerId = User.UserId();

            var vm = new EditVm();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customer = await db.Customers.SingleAsync(x => x.Id == customerId);

                vm.DefaultIncomingOpenUrl = customer.DefaultIncomingOpenUrl;
                vm.DefaultOutgoingOpenUrl = customer.DefaultOutgoingOpenUrl;

            }
            return View("Edit", vm);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditVm model)
        {
            var customerId = User.UserId();

            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customer = await db.Customers.SingleAsync(x => x.Id == customerId);

                if (customer.DefaultOutgoingOpenUrl != model.DefaultOutgoingOpenUrl ||
                    customer.DefaultIncomingOpenUrl != model.DefaultIncomingOpenUrl)
                {
                    customer.UrlsChangedDate = DateTime.Now;
                    customer.DefaultOutgoingOpenUrl = model.DefaultOutgoingOpenUrl;
                    customer.DefaultIncomingOpenUrl = model.DefaultIncomingOpenUrl;
                    await db.SaveChangesAsync();
                }

                TempData["SuccessMessage"] = "Ændringer gemt";
                return RedirectToAction("Index");


            }
        }

        public async Task<ActionResult> Users()
        {
            if (Session["IpvisibleAuthHeader"] == null)
            {
                TempData["ErrorMessage"] = "Session udløbet. Log ind igen";
                return RedirectToAction("Login", "Account");
            }
            var customerId = User.UserId();
            var ipvisionConsumer = new IpvisionApiConsumer();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customer = await db.Customers.SingleAsync(x => x.Id == customerId);
                var disabledUsers = await db.DisabledMitelUsers.Where(x => x.CustomerId == customerId).ToListAsync();
                var allUsers = ipvisionConsumer.GetDomainUsers(customer.Domain);

                var usersWithStatus = allUsers.Select(x => new UserWithStatus()
                {
                    MitelUser = x,
                    IsDisabled = disabledUsers.FirstOrDefault(w => w.MitelUserId == x.UserId) != null
                }).ToList();

                var vm = new UsersVm()
                {
                    Users = usersWithStatus
                };

                return View(vm);

            }
        }

        [HttpPost]
        public async Task<ActionResult> EnableOrDisableUser(string mitelUserId)
        {
            using (var db = new IpvisionCrmApiDbEntities())
            {
                try
                {
                    var ipvisionConsumer = new IpvisionApiConsumer();
                    var customerId = User.UserId();
                    var customer = await db.Customers.SingleAsync(x => x.Id == customerId);

                    var disabledUser = await db.DisabledMitelUsers.SingleOrDefaultAsync(x =>
                        x.MitelUserId == mitelUserId && x.CustomerId == customerId);
                    if (disabledUser == null)
                    {
                        var allUsers = ipvisionConsumer.GetDomainUsers(customer.Domain);
                        var user = allUsers.First(x => x.UserId == mitelUserId);
                        db.DisabledMitelUsers.Add(new DisabledMitelUser()
                        {
                            CustomerId = customerId,
                            Id = Guid.NewGuid(),
                            MitelUserId = mitelUserId,
                            Email = user.Email
                        });
                    }
                    else
                    {
                        db.DisabledMitelUsers.Remove(disabledUser);
                    }

                    await db.SaveChangesAsync();
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] =
                        "Kunne ikke ændre status for bruger. Forsøg igen, eller kontakt ipvision";
                    return RedirectToAction("Users");
                }
            }

            TempData["SuccessMessage"] = "Brugerstatus ændret";
            return RedirectToAction("Users");
        }
    }
}

ipvisionCrmApi/Views/ClientSettings/Edit.cshtml
@model ipvisionCrmApi.ViewModels.ClientSettings.EditVm
@{
    ViewBag.Title = "Klientindstillinger";
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Klientindstillinger
            </h3>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col">
            <div class="alert alert-light alert-elevate fade show" role="alert">
                <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
                <div class="alert-text">
                    På denne side kan du konfigurere standard-indstillinger pop-up klienten.
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            URL'er
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Edit", "ClientSettings", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Udgående opkald</label>
                                    @Html.TextBoxFor(x => x.DefaultOutgoingOpenUrl, new { @class = "form-control" })
                                    <p class="small">Du kan bruge teksten: [CALLED-ID] i URL'en. Dette vil blive udskiftet med det nummer der ringes til.</p>
                                </div>
                                <div class="form-group">
                                    <label>Besvarede opkald</label>
                                    @Html.TextBoxFor(x => x.DefaultIncomingOpenUrl, new {@class="form-control"})
                                    <p class="small">Du kan bruge teksten: [CALLER-ID] i URL'en. Dette vil blive udskiftet med det nummer der ringer ind.</p>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-success">Gem ændringer</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ipvisionCrmApi/Views/ClientSettings/Users.cshtml
@model ipvisionCrmApi.ViewModels.ClientSettings.UsersVm
@{
    ViewBag.Title = "Brugere";
}

<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Brugere
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <a href="/" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="@Url.Action("Index","ClientSettings")" class="kt-subheader__breadcrumbs-link">
                        Klientindstillinger
                    </a>
            </div>
        </div>
    </div>
</div>
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <div class="row">
        <div class="col-12">

            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Brugere
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <table class="table table-striped- table-bordered table-hover table-registrations" id="kt_table_1">
                        <thead>
                        <tr>
                            <th>Email</th>
                            <th>Navn</th>
                            <th>Status</th>
                        </tr>
                        </thead>

                        <tbody>
                            @foreach (var contact in Model.Users)
                            {
                                var btnClass = contact.IsDisabled ? "btn-danger" : "btn-success";
                                var btnText = contact.IsDisabled ? "Deaktiveret" : "Aktiveret";
                                <tr>
                                    <td>@contact.MitelUser.Email</td>
                                    <td>@contact.MitelUser.Name</td>
                                    <td>
                                        @using (Html.BeginForm("EnableOrDisableUser", "ClientSettings", FormMethod.Post))
                                        {
                                            <input type="hidden" name="mitelUserId" value="@contact.MitelUser.UserId"/>
                                            <button type="submit" class="btn btn-block @btnClass">@btnText</button>
                                        }
                                    </td>
                                </tr>
                            }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>


</div>
@section scripts
{
    <script>
        var table = $('#kt_table_1');

        // begin first table
        var dt = table.DataTable({
            "order": [[0, "asc"]],
            "iDisplayLength": 100
        });
    </script>
}