ipvisionCrmApi/ViewModels/Contacts/ImportResultItemVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.Data;

namespace ipvisionCrmApi.ViewModels.Contacts
{
    public class ImportResultItemVm
    {
        public int Line { get; set; }
        public bool IsInError { get; set; }
        public string ErrorMessage { get; set; }
        public InternalCrmContact ExistingCrmContact { get; set; }
        public InternalCrmContact ResultCrmContact { get; set; }
    }
}

ipvisionCrmApi/ViewModels/Contacts/ImportResultVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ipvisionCrmApi.ViewModels.Contacts
{
    public class ImportResultVm
    {
        public HttpPostedFileBase File { get; set; }
        public List<ImportResultItemVm> ResultItems { get; set; }
    }
}

ipvisionCrmApi/ViewModels/Contacts/IndexVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ipvisionCrmApi.Data;

namespace ipvisionCrmApi.ViewModels.Contacts
{
    public class IndexVm
    {
        public List<InternalCrmContact> Contacts { get; set; }
    }
}

ipvisionCrmApi/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using CsvHelper.Configuration;
using ipvisionCrmApi.Data;
using ipvisionCrmApi.Extensions;
using ipvisionCrmApi.Models.CsvModels;
using ipvisionCrmApi.ViewModels.Contacts;

namespace ipvisionCrmApi.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        // GET: Contacts
        public async Task<ActionResult> Index()
        {
            var customerId = User.UserId();
            var vm = new IndexVm();
            using (var db = new IpvisionCrmApiDbEntities())
            {
                vm.Contacts = await db.InternalCrmContacts.Where(x => x.CustomerId == customerId).ToListAsync();
            }
            return View(vm);
        }

        public ActionResult Import()
        {
            return View();
        }

        public async Task<PartialViewResult> GetUploadBatchResult(HttpPostedFileBase file)
        {
            // extract only the filename
            var fileName = Path.GetFileName(file.FileName).ToLower().Replace(".csv", "") + Guid.NewGuid() + ".csv";
            // store the file inside ~/App_Data/uploads folder
            var path = Path.Combine(Server.MapPath("~/App_Data/TEMP/"), fileName);
            file.SaveAs(path);

            var vms = await GetImportResult(path);

            System.IO.File.Delete(path);

            var viewModel = new ImportResultVm()
            {
                File = file,
                ResultItems = vms
            };

            return PartialView("_ImportResultPartial", viewModel);
        }


        [HttpPost]
        public async Task<ActionResult> Import(HttpPostedFileBase file, string deleteExisting)
        {
            // extract only the filename
            var fileName = Path.GetFileName(file.FileName);
            // store the file inside ~/App_Data/uploads folder
            var path = Path.Combine(Server.MapPath("~/App_Data/TEMP"), fileName);
            file.SaveAs(path);

            var vms = await GetImportResult(path);

            var customerId = User.UserId();

            using (var db = new IpvisionCrmApiDbEntities())
            {
                if (deleteExisting == "on")
                {
                    var existing = await db.InternalCrmContacts.Where(x => x.CustomerId == customerId).ToListAsync();
                    foreach (var c in existing)
                    {
                        db.InternalCrmContacts.Remove(c);
                    }
                }
                foreach (var contact in vms.Where(x => !x.IsInError))
                {
                    try
                    {
       
                        db.InternalCrmContacts.Add(new InternalCrmContact()
                        {
                            Phone1 = contact.ResultCrmContact.Phone1,
                            Phone2 = contact.ResultCrmContact.Phone2,
                            Phone3 = contact.ResultCrmContact.Phone3,
                            Phone4 = contact.ResultCrmContact.Phone4,
                            Email = contact.ResultCrmContact.Email,
                            Name = contact.ResultCrmContact.Name,
                            InternalCrmId1 = contact.ResultCrmContact.InternalCrmId1,
                            InternalCrmId2 = contact.ResultCrmContact.InternalCrmId2,
                            InternalCrmId3 = contact.ResultCrmContact.InternalCrmId3,
                            InternalCrmId4 = contact.ResultCrmContact.InternalCrmId4,
                            InternalCrmId5 = contact.ResultCrmContact.InternalCrmId5,
                            InternalCrmId6 = contact.ResultCrmContact.InternalCrmId6,
                            CustomerId = customerId,

                        });

                        await db.SaveChangesAsync();

                    }
                    catch (Exception e)
                    {
                        var inError = contact.IsInError;
                        //TODO: Lav en side hvor det endelige resultat vises, inkl. hvilke linjer der fejlede
                    }

                }
            }



            System.IO.File.Delete(path);


            TempData["SuccessMessage"] = "Kontakter importeret.";
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View(new InternalCrmContact());
        }

        [HttpPost]
        public async Task<ActionResult> Create(InternalCrmContact model)
        {
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customerId = User.UserId();
                model.CustomerId = customerId;
                db.InternalCrmContacts.Add(model);
                await db.SaveChangesAsync();
                TempData["SuccessMessage"] = "Kontakt oprettet";
                return RedirectToAction("Index");
            }
        }

        public async Task<ActionResult> Edit(long id)
        {
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customerId = User.UserId();
                var contact =
                    await db.InternalCrmContacts.FirstOrDefaultAsync(x => x.Id == id && x.CustomerId == customerId);
                if (contact == null)
                {
                    TempData["ErrorMessage"] = "Kontakt ikke fundet";
                    return RedirectToAction("Index");
                }

                return View(contact);
            }

        }

        [HttpPost]
        public async Task<ActionResult> Edit(InternalCrmContact model)
        {
            using (var db = new IpvisionCrmApiDbEntities())
            {
                var customerId = User.UserId();
                var contact =
                    await db.InternalCrmContacts.FirstOrDefaultAsync(x => x.Id == model.Id && x.CustomerId == customerId);
                if (contact == null)
                {
                    TempData["ErrorMessage"] = "Kontakt ikke fundet";
                    return RedirectToAction("Index");
                }

                contact.Name = model.Name;
                contact.Email = model.Email;
                contact.Phone1 = model.Phone1;
                contact.Phone2 = model.Phone2;
                contact.Phone3 = model.Phone3;
                contact.Phone4 = model.Phone4;

                contact.InternalCrmId1 = model.InternalCrmId1;
                contact.InternalCrmId2 = model.InternalCrmId2;
                contact.InternalCrmId3 = model.InternalCrmId3;
                contact.InternalCrmId4 = model.InternalCrmId4;
                contact.InternalCrmId5 = model.InternalCrmId5;
                contact.InternalCrmId6 = model.InternalCrmId6;

                await db.SaveChangesAsync();
                TempData["SuccessMessage"] = "Ændringer gemt";

                return RedirectToAction("Index");
            }
        }

        public async Task<List<ImportResultItemVm>> GetImportResult(string path)
        {
            var vms = new List<ImportResultItemVm>();
            var westernEncoding = Encoding.GetEncoding("windows-1254");
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                NewLine = Environment.NewLine,
                Delimiter = ";",
                PrepareHeaderForMatch = args => args.Header.ToLower(),
                MissingFieldFound = null,
                HeaderValidated = null,
                Encoding = westernEncoding

            };
            using (var reader = new StreamReader(new FileStream(path, FileMode.Open), westernEncoding))
            using (var csv = new CsvReader(reader, config))
            {
                var records = csv.GetRecords<ContactCsvModel>();
                using (var db = new IpvisionCrmApiDbEntities())
                {
                    var index = 1;
                    foreach (var row in records)
                    {
                        try
                        {

                            if (!string.IsNullOrEmpty(row.Email) && !row.Email.IsValidEmail())
                            {
                                vms.Add(new ImportResultItemVm()
                                {
                                    IsInError = true,
                                    Line = index,
                                    ErrorMessage = "Forkert formateret mailadresse"
                                });
                                index++;
                                continue;
                            }

                            var vm = new ImportResultItemVm()
                            {
                                IsInError = false,
                                Line = index,
                            };

                            vm.ResultCrmContact = new InternalCrmContact()
                            {
                                Name = row.Name,
                                Phone1 = row.Phone,
                                Phone2 = row.Phone2,
                                Phone3 = row.Phone3,
                                Phone4 = row.Phone4,
                                Email = row.Email,
                                InternalCrmId1 = row.Internalcrmid1,
                                InternalCrmId2 = row.Internalcrmid2,
                                InternalCrmId3 = row.Internalcrmid3,
                                InternalCrmId4 = row.Internalcrmid4,
                                InternalCrmId5 = row.Internalcrmid5,
                                InternalCrmId6 = row.Internalcrmid6
                            };

                            vms.Add(vm);

                        }
                        catch (Exception e)
                        {

ipvisionCrmApi/Views/Contacts/Create.cshtml
@model ipvisionCrmApi.Data.InternalCrmContact
@{
    ViewBag.Title = "Opret kontakt";
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Opret ny kontakt
            </h3>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <div class="row">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Kontaktoplysninger
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Create", "Contacts", FormMethod.Post))
                            {
                                @Html.Partial("Partials/_CreateEdit", Model)
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-success">Opret kontakt</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ipvisionCrmApi/Views/Contacts/Edit.cshtml
@model ipvisionCrmApi.Data.InternalCrmContact
@{
    ViewBag.Title = "Redigér kontakt";
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Opret ny kontakt
            </h3>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <div class="row">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Kontaktoplysninger
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Edit", "Contacts", FormMethod.Post))
                            {
                                @Html.Partial("Partials/_CreateEdit", Model)
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-success">Gem ændringer</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

ipvisionCrmApi/Views/Contacts/Import.cshtml
@{
    ViewBag.Title = "Import / sync kontakter";
}
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Importer kontakter fra CSV
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="@Url.Action("Index")" class="kt-subheader__breadcrumbs-link">
                    Kontakter
                </a>
            </div>
        </div>
    </div>
</div>

<div class="kt-container  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col">
            <div class="alert alert-light alert-elevate fade show" role="alert">
                <div class="alert-icon"><i class="flaticon-warning kt-font-brand"></i></div>
                <div class="alert-text">
                    <br />
                    Upload en CSV fil med organisationens kontakter. Sæt hak i "Slet eksisterende kontakter", hvis du laver en fuld upload. Eksisterende kontakter vil ikke blive opdateret - alle kontakter i filen vil blive oprettet, selvom de findes i forvejen. Første linje i CSV filen skal indeholde følgende headers, i vilkårlig rækkefølge:
                    <br />
                    <br />
                    <strong>"name", "email", "phone", "phone2", "phone3", "phone4" "internalCrmId1", "internalCrmId2", "internalCrmId3", "internalCrmId4", "internalCrmId5", "internalCrmId6"</strong>
                    <br />
                    <br />
                    <strong>NB!</strong> Telefonnumre skal indeholde landekode med "+" foran.
                    <br />
                    <br />
                    <a href="/ipvision-CRM-Middleware-API-Documentation.pdf" target="_blank">Klik her for at se API-dokumentation for at uploade kontakter</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Vælg den CSV fil der indeholder kontaktdata.
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Import", "Contacts", FormMethod.Post, new { enctype = "multipart/form-data", id = "import-form" }))
                            {
                                <div class="form-group row">
                                    <div class="col-lg-12">
                                        <label class="kt-checkbox">
                                            <input type="checkbox" name="deleteExisting" /> Slet eksisterende kontakter
                                            <span></span>
                                        </label>
                                    </div>
                                </div>
                                <input type="file" name="file" style="display: none" id="file" />
                            }

                            <div class="dropzone dropzone-default dropzone-brand" id="kt_dropzone_1">
                                <div class="dropzone-msg dz-message needsclick">
                                    <h3 class="dropzone-msg-title">Træk og slip CSV fil hertil</h3>
                                    <span class="dropzone-msg-desc">Vi vil vise dig resultatet af importen, før du accepterer og sætter importen i gang.</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" id="import-results" style="display: none">
        <div class="col">
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Dette vil være resultatet af at uploade CSV filen
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <div class="row">
                        <div class="col-xs-1 m-auto" id="import-result-spinner">
                            <div class="kt-spinner kt-spinner--v2 kt-spinner--lg kt-spinner--brand"></div>
                        </div>
                        <div class="col-sm-12" id="import-result-container"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>

        function FileListItem(a) {
            a = [].slice.call(Array.isArray(a) ? a : arguments)
            for (var c, b = c = a.length, d = !0; b-- && d;) d = a[b] instanceof File
            if (!d) throw new TypeError("expected argument to FileList is File or array of File objects")
            for (b = (new ClipboardEvent("")).clipboardData || new DataTransfer; c--;) b.items.add(a[c])
            return b.files
        }

        $('#kt_dropzone_1').dropzone({
            url: "@Url.Action("GetUploadBatchResult")", // Set the url for your upload script location
            paramName: "file", // The name that will be used to transfer the file
            maxFiles: 1,
            acceptedFiles:'.csv',
            maxFilesize: 5, // MB
            addRemoveLinks: true,
            init: function() {
                this.on("success", function(file, response) {
                        $("#import-result-container").html(response);
                    }),
                    this.on("processing", function (file, response) {
                        $("#import-result-container").html("");
                        $("#import-result-spinner").show();
                        $("#import-results").show();
                    }),
                    this.on("complete", function(file, response) {
                        $("#import-result-spinner").hide();
                    }),
                    this.on("reset", function (file, response) {
                        $("#import-results").hide();
                        $("#import-result-spinner").hide();
                    })
            },
            accept: function (file, done) {
                done();
                var fileVal = document.getElementById("file");
                var files = [
                    file
                ];
                fileVal.files = new FileListItem(files);

            }
        });

        //$("form#import-form").submit(function(e) {
        //    e.preventDefault();
        //    var formData = new FormData(this);
        //    var url = $(this).attr("action");

        //    function postSuccess(data) {

        //    }
        //    function postError() {

        //    }
        //    function postComplete() {

        //    }
        //});

        function StartImport() {
            $(".start-import-btn").addClass('kt-spinner kt-spinner--right kt-spinner--sm kt-spinner--light').attr('disabled', true);
            $("#import-form").submit();
        }

    </script>
}

ipvisionCrmApi/Views/Contacts/Index.cshtml
@using System.Globalization
@model ipvisionCrmApi.ViewModels.Contacts.IndexVm
@{
    ViewBag.Title = "Kontakter";
}

<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Kontaktliste
            </h3>
            <div class="kt-subheader__breadcrumbs">
                <a href="/" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                @*<span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="@Url.Action("Index","Locations")" class="kt-subheader__breadcrumbs-link">
                        Locations
                    </a>*@
            </div>
        </div>
        <div class="kt-subheader__toolbar">
            <div class="kt-subheader__wrapper">
                <a href="@Url.Action("Create")" class="btn kt-subheader__btn-primary">
                    Opret kontakt manuelt
                </a>
                <a href="@Url.Action("Import")" class="btn kt-subheader__btn-primary">
                    Importer kontakter
                </a>
            </div>
        </div>
    </div>
</div>
<div class="kt-container  kt-grid__item kt-grid__item--fluid">

    <div class="row">
        <div class="col-12">

            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Kontakter
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">
                    <table class="table table-striped- table-bordered table-hover table-registrations" id="kt_table_1">
                        <thead>
                        <tr>
                            <th>Email</th>
                            <th>Navn</th>
                            <th>Telefon 1</th>
                            <th>Telefon 2</th>
                            <th>Telefon 3</th>
                            <th>Telefon 4</th>
                            <th>Internt CRM ID 1</th>
                            <th>Internt CRM ID 2</th>
                            <th>Internt CRM ID 3</th>
                            <th>Internt CRM ID 4</th>
                            <th>Internt CRM ID 5</th>
                            <th>Internt CRM ID 6</th>
                            <th>Redigér</th>
                        </tr>
                        </thead>

                        <tbody>
                            @foreach (var contact in Model.Contacts)
                            {
                                <tr>
                                    <td>@contact.Email</td>
                                    <td>@contact.Name</td>
                                    <td>@contact.Phone1</td>
                                    <td>@contact.Phone2</td>
                                    <td>@contact.Phone3</td>
                                    <td>@contact.Phone4</td>
                                    <td>@contact.InternalCrmId1</td>
                                    <td>@contact.InternalCrmId2</td>
                                    <td>@contact.InternalCrmId3</td>
                                    <td>@contact.InternalCrmId4</td>
                                    <td>@contact.InternalCrmId5</td>
                                    <td>@contact.InternalCrmId6</td>
                                    <td><a href="@Url.Action("Edit", new {id=contact.Id})" class="btn btn-warning">Redigér</a></td>
                                </tr>
                            }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>


</div>
@section scripts{
    <script>
        var table = $('#kt_table_1');

        // begin first table
        var dt = table.DataTable({
            "order": [[0, "asc"]],
            "iDisplayLength": 100
        });



    </script>
}

ipvisionCrmApi/Views/Contacts/_ImportResultPartial.cshtml
@model ipvisionCrmApi.ViewModels.Contacts.ImportResultVm
@{
    var items = Model.ResultItems;
    var errorCount = items.Count(x => x.IsInError);
}
<div class="row">
    <div class="col-sm-12">
        @if (errorCount > 0)
        {
            <div class="alert alert-danger" role="alert">
                <div class="alert-text">Fandt fejl i @errorCount rækker! Venligst gennemgå nedenstående resultat, inden du bekræfter import.</div>
            </div>
        }
        <div class="form-group text-center kt-margin-t-10">
            <button type="submit" onclick="StartImport();" class="btn btn-lg btn-brand start-import-btn">Bekræft og start import!</button>
        </div>
        <table class="table table-striped table-bordered table-hover" id="import-result-table">
            <thead>
                <tr>
                    <th>Række#</th>
                    <th>Status</th>
                    <th>Status tekst</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in items)
                {
                    var statusText = line.IsInError ? "Fejl i .csv række" : line.ExistingCrmContact == null ? "Ny kontakt" : "Update";
                    var statusClass = line.IsInError ? "btn-label-danger" : line.ExistingCrmContact == null ? "btn-label-success" : "btn-label-warning";
                    <tr>
                        <td>@(line.Line +1)</td>
                        <td><span class="btn btn-bold btn-block btn-sm btn-font-sm  @statusClass">@statusText</span></td>
                        @if (line.IsInError)
                        {
                            var errorMessage = !string.IsNullOrEmpty(line.ErrorMessage) ? line.ErrorMessage : "Check rækken for potentielle fejl";

                            <td>
                                <p style="color: #d33f49">@errorMessage</p>
                            </td>
                        }
                        @if (line.ResultCrmContact != null)
                        {
                            <td>
                                <p>Linje OK</p>

                            </td>
                        }


                    </tr>

                }
            </tbody>
        </table>
        <div class="form-group text-center kt-margin-t-10">
            <button type="submit" onclick="StartImport();" class="btn btn-lg btn-brand start-import-btn">Bekræft og start import!</button>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#import-result-table").DataTable();

    });
</script>